version: 0.0
os: linux
files:
  - source: confs/nginx/vhost.conf
    destination: /etc/nginx/conf.d/vhost.conf
  - source: confs/nginx/nginx.repo
    destination: /etc/yum.repos.d/nginx.repo
  - source: confs/php-fpm/vhost.conf
    destination: /etc/php-fpm.d/vhost.conf
  - source: /
    destination: /var/www/app-v1
permissions:
  - object: /var/www/app-v1
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
hooks:
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
    - location: scripts/stop_server.sh
  ApplicationStart:
    - location: scripts/start_server.sh
    - location: scripts/register_with_elb.sh
