version: 0.0
os: linux
files:
  - source: confs/nginx/default.conf
    destination: /etc/nginx/conf.d
  - source: confs/nginx/nginx.repo
    destination: /etc/yum.repos.d
  - source: confs/php-fpm/www.conf
    destination: /etc/php-fpm.d
  - source: /
    destination: /var/www/app-v1
permissions:
  - object: /var/www/app-v1
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
  ApplicationStart:
    - location: scripts/start_server.sh
